import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ebe7e5",
        "surface": "#fff8f5",
        "on-error-container": "#93000a",
        "secondary": "#745850",
        "on-secondary": "#ffffff",
        "primary-container": "#ffd9de",
        "on-surface-variant": "#4d4635",
        "on-primary-fixed-variant": "#574500",
        "surface-container-highest": "#e5e2df",
        "inverse-primary": "#e9c349",
        "surface-container-low": "#fbf2ed",
        "on-primary": "#ffffff",
        "background": "#fff8f5",
        "tertiary-fixed": "#eae2d0",
        "on-secondary-fixed": "#2a1610",
        "inverse-surface": "#31302f",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#795c54",
        "on-primary-container": "#3d0014",
        "on-background": "#1c1b1a",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#4a4538",
        "surface-variant": "#e5e2df",
        "surface-tint": "#7d2d3d",
        "secondary-container": "#fed7cd",
        "inverse-on-surface": "#f4f0ed",
        "tertiary-container": "#bab2a2",
        "outline": "#7f7663",
        "primary": "#7d2d3d",
        "tertiary": "#645e50",
        "secondary-fixed-dim": "#e3beb4",
        "primary-fixed": "#ffe088",
        "on-surface": "#1c1b1a",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#cec6b5",
        "error": "#ba1a1a",
        "outline-variant": "#d0c5af",
        "primary-fixed-dim": "#e9c349",
        "on-tertiary-fixed": "#1f1b10",
        "surface-dim": "#e1d8d4",
        "secondary-fixed": "#ffdbd1",
        "on-tertiary-fixed-variant": "#4b4639",
        "surface-container": "#f5ece8",
        "on-secondary-fixed-variant": "#5b4139",
        "on-primary-fixed": "#241a00",
        "surface-bright": "#fff8f5",
      }
    },
  },
  plugins: [],
};
export default config;